package tare_tablas_hash;


import java.util.HashMap;
import java.util.StringTokenizer;

public class frm_tablashash extends javax.swing.JFrame {

    /**
     * Creates new form frm_HashForm
     */
    
    HashMap<Integer, String> hash;
    public frm_tablashash() {
        initComponents();
        hash = new HashMap();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ejecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_de_texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese su codigo en C++");

        ejecutar.setText("Ejecutar");
        ejecutar.setToolTipText("");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        area_de_texto.setColumns(20);
        area_de_texto.setRows(5);
        jScrollPane1.setViewportView(area_de_texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(ejecutar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ejecutar)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        // TODO add your handling code here:
         ejecucion_h(area_de_texto.getText());
    }//GEN-LAST:event_ejecutarActionPerformed
 public void ejecucion_h(String texto)
    {
        //intente separar por ; pero en donde separo por lineas, hacerlo pero en donde ya tengo las lineas separadas.
        int CantidadLineas = 0, lector = 0, index = 0;
        String[] lineas = area_de_texto.getText().split("\\r?\\n");
        String palabras[] = new String[100];
        String sec[]  = new String [100];
        CantidadLineas = lineas.length;
        for(int t =0; t<CantidadLineas;t++)
        {
            StringTokenizer tokens = new StringTokenizer(lineas[t]);
            while(tokens.hasMoreTokens())
            {
                palabras[t]=tokens.nextToken();
                
                StringTokenizer token2 = new StringTokenizer(palabras[t], ";", true);
                while(token2.hasMoreTokens())
                {
                    sec[t]=token2.nextToken();
                   
                    
                    
                    index = lineas[t].indexOf(palabras[t]);
                    System.out.println(" la posicion es: "+t+", " + index+ " para la palabra: " + sec[t]);

                    String fila = String.valueOf(t);
                    String columna = String.valueOf(index);
                    String codigo = fila+columna;
                    int codigo_hash = Integer.parseInt(codigo);

                    hash.put(codigo_hash, palabras[t]);
                }
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_tablashash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_tablashash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_tablashash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_tablashash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_tablashash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_de_texto;
    private javax.swing.JButton ejecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
